Repository apptolast/FamilyFilmApp, pull requests merged in 2025-03, with the labels that each got.

#319 v0.3.3
  .editorconfig
  app/build.gradle.kts
  app/src/main/java/com/apptolast/familyfilmapp/di/GoogleSignInModule.kt
  app/src/main/java/com/apptolast/familyfilmapp/di/RepositoryModule.kt
  app/src/main/java/com/apptolast/familyfilmapp/repositories/FirebaseAuthRepository.kt
  app/src/main/java/com/apptolast/familyfilmapp/repositories/datasources/FirebaseDatabaseDatasource.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/components/dialogs/EmailFieldDialog.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/GroupsScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/login/LoginScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/login/components/GoogleButtonContent.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/profile/ProfileScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/sharedViewmodel/AuthViewModel.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/theme/Type.kt
  app/src/main/res/drawable/ic_google.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
  distribution/whatsnew/whatsnew-en-US 
  gradle.properties
  gradle/libs.versions.toml
Labels: deploy

#320 FFA-162 Fix Google sign in
  .github/workflows/deploy.yml
  app/build.gradle.kts
  app/src/main/java/com/apptolast/familyfilmapp/di/GoogleSignInModule.kt
  app/src/main/java/com/apptolast/familyfilmapp/repositories/FirebaseAuthRepository.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/profile/ProfileScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/sharedViewmodel/AuthViewModel.kt
  distribution/whatsnew/whatsnew-es-ES
  gradle/libs.versions.toml
Labels: bug

#321 v0.3.4
  app/build.gradle.kts
  app/src/main/java/com/apptolast/familyfilmapp/di/GoogleSignInModule.kt
  app/src/main/java/com/apptolast/familyfilmapp/repositories/FirebaseAuthRepository.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/profile/ProfileScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/sharedViewmodel/AuthViewModel.kt
  distribution/whatsnew/whatsnew-es-ES
  gradle/libs.versions.toml
Labels: deploy

#322 FFA-163 Improve deploy and clean code
  .github/workflows/deploy.yml
  app/build.gradle.kts
  app/src/main/java/com/apptolast/familyfilmapp/ui/sharedViewmodel/AuthViewModel.kt
Labels: enhancement

#323 v0.3.5
  .github/workflows/deploy.yml
  app/build.gradle.kts
  app/src/main/java/com/apptolast/familyfilmapp/ui/sharedViewmodel/AuthViewModel.kt
  gradle/libs.versions.toml
Labels: deploy

#324 FFA-164 Fix production issues
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/com/apptolast/familyfilmapp/FamilyFilmApp.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/local/Genre.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/local/User.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/local/types/MovieStatus.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/request/AddGroupBody.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/request/AddMemberBody.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/request/RemoveMemberBody.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/request/SearchMovieByNameBody.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/request/UpdateGroupNameBody.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/response/AddGroupRemote.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/response/AddMemberRemote.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/response/GenreRemote.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/response/GroupRemote.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/response/MovieCatalogueRemote.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/response/MovieRemote.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/response/UserRemote.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/remote/response/UserResponseRemote.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/room/UserTable.kt
  app/src/main/java/com/apptolast/familyfilmapp/room/converters/MapStatusConverter.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/detail/DetailScreenViewModel.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/detail/DetailsScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/GroupViewModel.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/profile/ProfileScreen.kt
Labels: bug

#327 FFA-164 Improve profile screen layout and enable emulator connections
  .github/workflows/deploy.yml
  .gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/apptolast/familyfilmapp/di/FirebaseModule.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/profile/ProfileScreen.kt
  app/src/main/res/xml/network_security_config.xml
  distribution/whatsnew/whatsnew-en-GB
  distribution/whatsnew/whatsnew-es-ES
Labels: bug

#328 v0.3.11
  .github/workflows/deploy.yml
  .gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/apptolast/familyfilmapp/di/FirebaseModule.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/profile/ProfileScreen.kt
  app/src/main/res/xml/network_security_config.xml
  distribution/whatsnew/whatsnew-en-GB
  distribution/whatsnew/whatsnew-es-ES
Labels: deploy

#329 v0.3.12
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/apptolast/familyfilmapp/MainActivity.kt
  app/src/main/java/com/apptolast/familyfilmapp/exceptions/CustomException.kt
  app/src/main/java/com/apptolast/familyfilmapp/navigation/AppNavigation.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/GroupsScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/components/HorizontalScrollableMovies.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/HomeScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/HomeViewModel.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/MovieItem.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/login/LoginScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/profile/ProfileScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/theme/Theme.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/theme/Type.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
Labels: deploy

#334 FFA-168 Add Crashlytics integration and logging configuration
  app/src/main/java/com/apptolast/familyfilmapp/FamilyFilmApp.kt
  app/src/main/java/com/apptolast/familyfilmapp/repositories/datasources/FirebaseDatabaseDatasource.kt
  app/src/main/java/com/apptolast/familyfilmapp/utils/ReleaseTree.kt
Labels: enhancement

#333 FFA-126 Implement Admob and banner
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/apptolast/familyfilmapp/MainActivity.kt
  app/src/main/java/com/apptolast/familyfilmapp/navigation/AppNavigation.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/components/AdaptiveBanner.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/GroupsScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/components/HorizontalScrollableMovies.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/HomeScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/MovieItem.kt
  gradle/libs.versions.toml
Labels: enhancement

#332 FFA-166 Handle auth errors and improve error messages
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  app/build.gradle.kts
  app/src/main/java/com/apptolast/familyfilmapp/di/RepositoryModule.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/local/User.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/room/UserTable.kt
  app/src/main/java/com/apptolast/familyfilmapp/repositories/FirebaseAuthRepository.kt
  app/src/main/java/com/apptolast/familyfilmapp/repositories/datasources/FirebaseDatabaseDatasource.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/detail/DetailsScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/GroupsScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/components/GroupCard.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/login/LoginScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/profile/ProfileScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/sharedViewmodel/AuthViewModel.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#341 FFA-170 Refactor details screen
  app/src/main/java/com/apptolast/familyfilmapp/navigation/AppNavigation.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/detail/DetailsScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/detail/DetailsViewModel.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/GroupsScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/components/HorizontalScrollableMovies.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/HomeScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/HomeUiState.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/HomeViewModel.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/MovieItem.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/MoviePagingSource.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/profile/ProfileScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/theme/Color.kt
Labels: enhancement

#343 v0.3.13
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/apptolast/familyfilmapp/FamilyFilmApp.kt
  app/src/main/java/com/apptolast/familyfilmapp/MainActivity.kt
  app/src/main/java/com/apptolast/familyfilmapp/di/RepositoryModule.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/local/User.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/room/UserTable.kt
  app/src/main/java/com/apptolast/familyfilmapp/navigation/AppNavigation.kt
  app/src/main/java/com/apptolast/familyfilmapp/repositories/FirebaseAuthRepository.kt
  app/src/main/java/com/apptolast/familyfilmapp/repositories/datasources/FirebaseDatabaseDatasource.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/components/AdaptiveBanner.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/detail/DetailsScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/detail/DetailsViewModel.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/GroupsScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/components/GroupCard.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/components/HorizontalScrollableMovies.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/HomeScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/HomeUiState.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/HomeViewModel.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/MovieItem.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/home/MoviePagingSource.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/login/LoginScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/profile/ProfileScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/sharedViewmodel/AuthViewModel.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/theme/Color.kt
  app/src/main/java/com/apptolast/familyfilmapp/utils/ReleaseTree.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: deploy

#344 FFA-172 Correctly use user ID instead of UID
  app/build.gradle.kts
  app/src/main/java/com/apptolast/familyfilmapp/model/local/User.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/room/UserTable.kt
  app/src/main/java/com/apptolast/familyfilmapp/repositories/datasources/FirebaseDatabaseDatasource.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/GroupsScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/components/GroupCard.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/sharedViewmodel/AuthViewModel.kt
  distribution/whatsnew/whatsnew-en-GB
  distribution/whatsnew/whatsnew-es-ES
Labels: bug

#345 v0.3.14
  app/build.gradle.kts
  app/src/main/java/com/apptolast/familyfilmapp/model/local/User.kt
  app/src/main/java/com/apptolast/familyfilmapp/model/room/UserTable.kt
  app/src/main/java/com/apptolast/familyfilmapp/repositories/datasources/FirebaseDatabaseDatasource.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/GroupsScreen.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/screens/groups/components/GroupCard.kt
  app/src/main/java/com/apptolast/familyfilmapp/ui/sharedViewmodel/AuthViewModel.kt
  distribution/whatsnew/whatsnew-en-GB
  distribution/whatsnew/whatsnew-es-ES
Labels: deploy
